### ISSUE TITLE
Use motion sensor as a trigger

### ISSUE THREAD

**Issue by vdrover** [jasmas/homebridge-platform-blink-security#3]
@jasmas Is it possible to add support for the motion sensor so that when motion is detected I can launch an automation (turning on a light for example) in the Home app.

**Comment by jasmas** [comment]
Unfortunately, not really. This is implemented in systems like Hue by the Hue bridge making an API call to the Homekit hub as soon as it is alerted by the motion sensor. What we have is a black box (the sync module) and a reverse engineered API that the app uses to communicate with Blink servers. The API is only for interaction / requests initiated by the app, e.g., a user browsing videos, turning motion sensors on/off, etc.  

The alerting functionality of the app is actually implemented with standard push notifications which are sent out by blink's servers as soon as they become aware a new video is being / is about to be captured. (Actually based on when I receive alerts I think they only send them out when a new video has been completely recorded and is available for viewing.) 

The only way I can think to implement this with Homebridge would be to constantly poll the API to see if another video is available or possibly by polling the camera properties to see if the number of notifications has incremented. I discovered early on that blink also rate-limits requests to their servers, so I think this would be too slow to have any practical use and I'm also conscious of constant polling since many home networks are completely wireless.

Blink's own integration with IFTTT is reportedly too slow for practical use when it comes to the motion sensors. It looks like some users have been successful monitoring for the cameras to become active on the network, but I don't think that sort of solution can be implemented in the context of a homebridge platform. 
https://community.blinkforhome.com/t/ifttt-this-applet-usually-runs-within-a-few-hours/7683/19
